// docs/mockups/Zen-Sumi Design System/sensei_src/lib/impact.jsx
// Change impact reports — closes the loop on accepted recommendations.
//
// Two screens in one file:
//   ▸ ImpactReports — list of all reports + detail panel; verdict-coloured.
//   ▸ NegativeImpactAlert — the stand-alone red flag for a negative report.

const { useState: ciS } = React;

const VERDICT_META = {
  positive: { glyph: "好", color: "var(--success)",  label: "positive impact" },
  neutral:  { glyph: "並", color: "var(--ink-mute)", label: "no measurable effect" },
  negative: { glyph: "悪", color: "var(--accent)",   label: "negative impact" }
};

// ═══════════════════════════════════════════════════════════════════════
// SCREEN A · Change Impact Report (full list + detail)
// ═══════════════════════════════════════════════════════════════════════
function ObsImpact() {
  const reports = window.UPGRADES.impactReports;
  const [openId, setOpen] = ciS(reports[0].id);
  const r = reports.find(x => x.id === openId) || reports[0];

  return (
    <div className="sensei" data-screen-label="Observatory · Change impact"
         style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column',
                  background: 'var(--paper)', overflow: 'hidden' }}>

      <div style={{ padding: '22px 36px 18px', borderBottom: 'var(--hairline)',
                     display: 'flex', alignItems: 'center', gap: 22 }}>
        <div className="kanji" style={{ fontSize: 42, color: 'var(--accent)', lineHeight: 1 }}>果</div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 10.5, letterSpacing: '0.18em', color: 'var(--ink-mute)',
                         textTransform: 'uppercase', marginBottom: 5 }}>
            Observatory · Change impact
          </div>
          <h1 className="display" style={{ fontSize: 22, fontWeight: 400, margin: 0,
                                            color: 'var(--ink)' }}>
            Did sensei's advice actually work?
          </h1>
          <p style={{ fontSize: 12, color: 'var(--ink-soft)', margin: '4px 0 0',
                       maxWidth: 720, lineHeight: 1.55 }}>
            Each accepted recommendation gets a measurement window. FTR,
            corrections, tool usage and session duration are compared
            before vs after. The MOE panel writes the reasoning.
          </p>
        </div>
        <div style={{ paddingLeft: 22, borderLeft: 'var(--hairline)',
                       display: 'flex', gap: 22 }}>
          <UgMini n={reports.filter(r => r.verdict === "positive").length} l="positive" accent/>
          <UgMini n={reports.filter(r => r.verdict === "neutral").length} l="neutral"/>
          <UgMini n={reports.filter(r => r.verdict === "negative").length} l="negative"/>
        </div>
      </div>

      <div style={{ flex: 1, display: 'grid',
                     gridTemplateColumns: '300px 1fr',
                     minHeight: 0 }}>
        <aside style={{ borderRight: 'var(--hairline)', overflow: 'auto', padding: '8px 0' }}>
          {reports.map(rr => {
            const vm = VERDICT_META[rr.verdict];
            const open = openId === rr.id;
            return (
              <button key={rr.id} onClick={() => setOpen(rr.id)}
                      style={{ width: '100%', textAlign: 'left',
                                padding: '12px 18px',
                                background: open ? 'var(--paper-soft)' : 'transparent',
                                borderLeft: open ? `2px solid ${vm.color}`
                                                  : '2px solid transparent',
                                cursor: 'pointer' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <span className="kanji" style={{ fontSize: 13, color: vm.color }}>{vm.glyph}</span>
                  <span style={{ fontSize: 9.5, letterSpacing: '0.14em', color: vm.color,
                                  textTransform: 'uppercase' }}>{rr.verdict}</span>
                  <span style={{ flex: 1 }}/>
                  <span className="mono" style={{ fontSize: 10.5,
                                color: rr.ftrDelta >= 0 ? 'var(--success)' : 'var(--accent)' }}>
                    {rr.ftrDelta >= 0 ? "+" : ""}{Math.round(rr.ftrDelta*100)}%
                  </span>
                </div>
                <div style={{ fontSize: 12.5,
                               color: open ? 'var(--ink)' : 'var(--ink-soft)',
                               lineHeight: 1.4, marginTop: 6, fontWeight: 500 }}>
                  {rr.title}
                </div>
                <div className="mono" style={{ fontSize: 10, color: 'var(--ink-faint)',
                              marginTop: 4 }}>
                  {rr.window}
                </div>
              </button>
            );
          })}
        </aside>

        <main style={{ overflow: 'auto', padding: '28px 44px 36px' }}>
          <ImpactDetail r={r}/>
        </main>
      </div>
    </div>
  );
}

function ImpactDetail({ r }) {
  const vm = VERDICT_META[r.verdict];

  return (
    <div style={{ maxWidth: 800 }}>
      {/* Eyebrow */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12,
                     fontSize: 11, color: 'var(--ink-mute)', letterSpacing: '0.12em',
                     textTransform: 'uppercase', marginBottom: 12 }}>
        <span className="mono" style={{ letterSpacing: 0 }}>{r.recId}</span>
        <Sep/>
        <span className="mono" style={{ letterSpacing: 0 }}>{r.project}</span>
        <Sep/>
        <span>acted {r.acted}</span>
        <Sep/>
        <span>measured {r.measured}</span>
      </div>

      <h2 className="display" style={{ fontSize: 28, fontWeight: 300,
                                        lineHeight: 1.2, letterSpacing: '-0.015em',
                                        margin: '0 0 18px', color: 'var(--ink)' }}>
        {r.title}
      </h2>

      {/* Verdict pill + window */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 14,
                     marginBottom: 22 }}>
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8,
                       padding: '6px 12px',
                       background: `color-mix(in oklab, ${vm.color}, transparent 85%)`,
                       borderRadius: 18,
                       border: `1px solid color-mix(in oklab, ${vm.color}, transparent 70%)` }}>
          <span className="kanji" style={{ fontSize: 13, color: vm.color }}>{vm.glyph}</span>
          <span style={{ fontSize: 11, color: vm.color,
                          letterSpacing: '0.14em', textTransform: 'uppercase',
                          fontWeight: 500 }}>{vm.label}</span>
        </div>
        <span className="mono" style={{ fontSize: 11, color: 'var(--ink-mute)' }}>
          {r.window}
        </span>
      </div>

      {/* Before / after metric grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)',
                     gap: 1, background: 'var(--paper-edge)',
                     borderRadius: 6, overflow: 'hidden', marginBottom: 22 }}>
        <BeforeAfter label="First-Try-Right"
                     before={`${Math.round(r.baselineFtr*100)}%`}
                     after={`${Math.round(r.currentFtr*100)}%`}
                     delta={`${r.ftrDelta >= 0 ? "+" : ""}${Math.round(r.ftrDelta*100)}pp`}
                     positive={r.ftrDelta >= 0}/>
        <BeforeAfter label="Corrections / session"
                     before={r.baselineCorrections.toFixed(1)}
                     after={r.currentCorrections.toFixed(1)}
                     delta={`${r.correctionsDelta >= 0 ? "+" : ""}${r.correctionsDelta.toFixed(1)}`}
                     positive={r.correctionsDelta <= 0}/>
        <BeforeAfter label="Avg session"
                     before="—"
                     after={`${r.avgSessionDelta >= 0 ? "+" : ""}${r.avgSessionDelta} min`}
                     delta=""
                     positive={r.avgSessionDelta <= 0}/>
        <BeforeAfter label="Tool-usage shift"
                     before={Object.keys(r.toolUsageDelta).length === 0 ? "—" :
                             Object.keys(r.toolUsageDelta).length + " tools"}
                     after=""
                     delta=""
                     positive={true}/>
      </div>

      {/* Tool usage detail */}
      {Object.keys(r.toolUsageDelta).length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <div style={{ fontSize: 10, letterSpacing: '0.14em', color: 'var(--ink-mute)',
                         textTransform: 'uppercase', marginBottom: 10 }}>Tool usage delta</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
            {Object.entries(r.toolUsageDelta).map(([tool, d]) => (
              <div key={tool} style={{ display: 'flex', alignItems: 'center', gap: 10,
                                        padding: '6px 10px',
                                        background: 'var(--paper-soft)',
                                        border: 'var(--hairline)', borderRadius: 4 }}>
                <span className="mono" style={{ fontSize: 11.5, color: 'var(--ink)',
                              flex: 1 }}>{tool}</span>
                <ToolBar value={d}/>
                <span className="mono" style={{ fontSize: 11,
                              color: d >= 0 ? 'var(--success)' : 'var(--accent)',
                              minWidth: 48, textAlign: 'right' }}>
                  {d >= 0 ? "+" : ""}{d}%
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* MOE panel */}
      <div style={{ background: 'var(--paper-soft)', border: 'var(--hairline)',
                     borderLeft: `2px solid ${vm.color}`,
                     borderRadius: 6, padding: '18px 22px', marginBottom: 22 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
          <span className="kanji" style={{ fontSize: 14, color: 'var(--accent)' }}>議</span>
          <span style={{ fontSize: 10, letterSpacing: '0.14em', color: 'var(--ink-mute)',
                          textTransform: 'uppercase' }}>MOE panel reasoning</span>
          <span style={{ flex: 1 }}/>
          <span className="mono" style={{ fontSize: 10.5, color: 'var(--ink-mute)' }}>
            {r.moeReasoning.consensus}
          </span>
        </div>
        <div style={{ fontSize: 14, color: 'var(--ink)', lineHeight: 1.5,
                       fontWeight: 500, marginBottom: 8 }}>
          {r.moeReasoning.headline}
        </div>
        <p style={{ fontSize: 13, color: 'var(--ink-soft)', lineHeight: 1.65,
                     margin: '0 0 14px' }}>{r.moeReasoning.body}</p>

        {/* Per-model votes */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6,
                       paddingTop: 12, borderTop: 'var(--hairline)' }}>
          {r.moeReasoning.models.map((m, i) => {
            const mv = VERDICT_META[m.verdict];
            return (
              <div key={i} style={{ display: 'grid',
                                     gridTemplateColumns: '120px 14px 1fr',
                                     gap: 10, alignItems: 'flex-start' }}>
                <span className="mono" style={{ fontSize: 11, color: 'var(--ink)' }}>
                  {m.name}
                </span>
                <span className="kanji" style={{ fontSize: 12, color: mv.color,
                              marginTop: 1 }}>{mv.glyph}</span>
                <span style={{ fontSize: 11.5, color: 'var(--ink-soft)', lineHeight: 1.5 }}>
                  {m.note}
                </span>
              </div>
            );
          })}
        </div>

        {r.moeReasoning.suggestedRevision && (
          <div style={{ marginTop: 14, padding: '10px 12px',
                         background: 'var(--paper)', borderRadius: 4,
                         border: 'var(--hairline)' }}>
            <div style={{ fontSize: 10, letterSpacing: '0.14em', color: 'var(--accent)',
                           textTransform: 'uppercase', marginBottom: 4 }}>
              Suggested revision
            </div>
            <div style={{ fontSize: 12, color: 'var(--ink)', lineHeight: 1.55 }}>
              {r.moeReasoning.suggestedRevision}
            </div>
          </div>
        )}
      </div>

      {/* Actions */}
      <div style={{ display: 'flex', gap: 8, alignItems: 'center', paddingTop: 4 }}>
        {r.verdict === "negative" ? (
          <>
            <button style={{ padding: '9px 18px', fontSize: 13,
                              background: 'var(--ink)', color: 'var(--paper)',
                              border: 'none', borderRadius: 6, cursor: 'pointer',
                              display: 'inline-flex', alignItems: 'center', gap: 8 }}>
              <span className="kanji" style={{ fontSize: 13, color: 'var(--accent)' }}>戻</span>
              Revert change
            </button>
            <FlatBtn glyph="改" label="Revise the rule"/>
          </>
        ) : (
          <FlatBtn glyph="改" label="Revise"/>
        )}
        <FlatBtn glyph="観" label="Keep monitoring"/>
        <span style={{ flex: 1 }}/>
        <FlatBtn glyph="納" label="Dismiss" subtle/>
      </div>
    </div>
  );
}

function BeforeAfter({ label, before, after, delta, positive }) {
  return (
    <div style={{ background: 'var(--paper-soft)', padding: '14px 16px' }}>
      <div style={{ fontSize: 9.5, letterSpacing: '0.14em', color: 'var(--ink-faint)',
                     textTransform: 'uppercase', marginBottom: 8 }}>{label}</div>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
        <span className="mono" style={{ fontSize: 11, color: 'var(--ink-mute)' }}>{before}</span>
        {after && <span style={{ fontSize: 11, color: 'var(--ink-faint)' }}>→</span>}
        {after && (
          <span className="display" style={{ fontSize: 17, fontWeight: 400,
                        color: 'var(--ink)' }}>{after}</span>
        )}
      </div>
      {delta && (
        <div className="mono" style={{ fontSize: 11,
                       color: positive ? 'var(--success)' : 'var(--accent)',
                       marginTop: 4 }}>{delta}</div>
      )}
    </div>
  );
}

function ToolBar({ value }) {
  const w = 80;
  const half = w / 2;
  const len = Math.min(half, Math.abs(value) / 50 * half);
  const positive = value >= 0;
  return (
    <svg width={w} height={8}>
      <line x1={half} y1={0} x2={half} y2={8} stroke="var(--paper-edge)" strokeWidth="1"/>
      <rect x={positive ? half : half - len} y={2} width={len} height={4}
            fill={positive ? 'var(--success)' : 'var(--accent)'} rx={1}/>
    </svg>
  );
}

// ═══════════════════════════════════════════════════════════════════════
// SCREEN B · Negative Impact Alert (focused on a single bad outcome)
// ═══════════════════════════════════════════════════════════════════════
function ObsNegativeAlert() {
  const reports = window.UPGRADES.impactReports;
  const r = reports.find(x => x.verdict === "negative") || reports[0];

  return (
    <div className="sensei" data-screen-label="Observatory · Negative impact alert"
         style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column',
                  background: 'var(--paper)', overflow: 'hidden' }}>

      {/* The alert banner */}
      <div style={{ background: 'var(--accent)',
                     padding: '14px 36px',
                     display: 'flex', alignItems: 'center', gap: 14,
                     color: 'var(--paper)' }}>
        <span className="kanji" style={{ fontSize: 22 }}>警</span>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 11, letterSpacing: '0.18em', textTransform: 'uppercase',
                         opacity: 0.8 }}>regression detected</div>
          <div style={{ fontSize: 14, fontWeight: 500 }}>
            A change you accepted on {r.acted} is hurting your FTR.
            Sensei surfaced this for review.
          </div>
        </div>
        <button style={{ fontSize: 11, color: 'var(--paper)',
                          background: 'rgba(255,255,255,0.15)', border: 'none',
                          padding: '6px 12px', borderRadius: 4, cursor: 'pointer' }}>
          dismiss
        </button>
      </div>

      <div style={{ flex: 1, overflow: 'auto', padding: '32px 60px 40px',
                     maxWidth: 920, margin: '0 auto', width: '100%' }}>

        {/* Headline */}
        <div style={{ fontSize: 11, color: 'var(--accent)', letterSpacing: '0.14em',
                       textTransform: 'uppercase', fontWeight: 500, marginBottom: 8 }}>
          Negative impact · {r.window}
        </div>
        <h1 className="display" style={{ fontSize: 32, fontWeight: 300, lineHeight: 1.2,
                                          letterSpacing: '-0.015em',
                                          margin: '0 0 12px', color: 'var(--ink)' }}>
          {r.title}
        </h1>
        <p style={{ fontSize: 14, color: 'var(--ink-soft)', lineHeight: 1.65, margin: '0 0 28px' }}>
          {r.moeReasoning.headline}
        </p>

        {/* The two big deltas */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr',
                       gap: 14, marginBottom: 28 }}>
          <DeltaCard label="First-Try-Right"
                     before={`${Math.round(r.baselineFtr*100)}%`}
                     after={`${Math.round(r.currentFtr*100)}%`}
                     delta={`${Math.round(r.ftrDelta*100)}pp`}
                     dir="down" bad/>
          <DeltaCard label="Corrections / session"
                     before={r.baselineCorrections.toFixed(1)}
                     after={r.currentCorrections.toFixed(1)}
                     delta={`+${r.correctionsDelta.toFixed(1)}`}
                     dir="up" bad/>
        </div>

        {/* Why — MOE reasoning */}
        <div style={{ background: 'var(--paper-soft)', border: 'var(--hairline)',
                       borderRadius: 6, padding: '20px 24px', marginBottom: 22 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
            <span className="kanji" style={{ fontSize: 14, color: 'var(--accent)' }}>議</span>
            <span style={{ fontSize: 10, letterSpacing: '0.14em', color: 'var(--ink-mute)',
                            textTransform: 'uppercase' }}>Why · MOE panel</span>
            <span style={{ flex: 1 }}/>
            <span className="mono" style={{ fontSize: 10.5, color: 'var(--accent)' }}>
              {r.moeReasoning.consensus}
            </span>
          </div>
          <p style={{ fontSize: 13, color: 'var(--ink)', lineHeight: 1.7,
                       margin: '0 0 16px' }}>{r.moeReasoning.body}</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8,
                         paddingTop: 14, borderTop: 'var(--hairline)' }}>
            {r.moeReasoning.models.map((m, i) => {
              const mv = VERDICT_META[m.verdict];
              return (
                <div key={i} style={{ display: 'grid',
                                       gridTemplateColumns: '130px 14px 1fr',
                                       gap: 12, alignItems: 'flex-start' }}>
                  <span className="mono" style={{ fontSize: 11, color: 'var(--ink)' }}>
                    {m.name}
                  </span>
                  <span className="kanji" style={{ fontSize: 12, color: mv.color }}>{mv.glyph}</span>
                  <span style={{ fontSize: 11.5, color: 'var(--ink-soft)', lineHeight: 1.55 }}>
                    {m.note}
                  </span>
                </div>
              );
            })}
          </div>
        </div>

        {/* Suggested revision */}
        {r.moeReasoning.suggestedRevision && (
          <div style={{ background: 'var(--paper)', border: '1px solid var(--accent)',
                         borderRadius: 6, padding: '16px 20px', marginBottom: 28 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
              <span className="kanji" style={{ fontSize: 14, color: 'var(--accent)' }}>改</span>
              <span style={{ fontSize: 10.5, letterSpacing: '0.14em', color: 'var(--accent)',
                              textTransform: 'uppercase', fontWeight: 500 }}>
                Recommended fix
              </span>
            </div>
            <div style={{ fontSize: 13, color: 'var(--ink)', lineHeight: 1.6 }}>
              {r.moeReasoning.suggestedRevision}
            </div>
          </div>
        )}

        {/* Actions */}
        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
          <button style={{ padding: '10px 20px', fontSize: 13,
                            background: 'var(--ink)', color: 'var(--paper)',
                            border: 'none', borderRadius: 6, cursor: 'pointer',
                            display: 'inline-flex', alignItems: 'center', gap: 8 }}>
            <span className="kanji" style={{ fontSize: 13, color: 'var(--accent)' }}>戻</span>
            Revert change
          </button>
          <button style={{ padding: '10px 20px', fontSize: 13,
                            background: 'var(--paper-soft)', color: 'var(--ink)',
                            border: 'var(--hairline)', borderRadius: 6, cursor: 'pointer',
                            display: 'inline-flex', alignItems: 'center', gap: 8 }}>
            <span className="kanji" style={{ fontSize: 13, color: 'var(--accent)' }}>改</span>
            Revise the rule
          </button>
          <FlatBtn glyph="観" label="Keep monitoring"/>
          <span style={{ flex: 1 }}/>
          <FlatBtn glyph="納" label="Dismiss" subtle/>
        </div>
      </div>
    </div>
  );
}

function DeltaCard({ label, before, after, delta, dir, bad }) {
  return (
    <div style={{ background: 'var(--paper-soft)', border: 'var(--hairline)',
                   borderRadius: 6, padding: '18px 22px' }}>
      <div style={{ fontSize: 10, letterSpacing: '0.14em', color: 'var(--ink-mute)',
                     textTransform: 'uppercase', marginBottom: 12 }}>{label}</div>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 12 }}>
        <span className="display" style={{ fontSize: 28, fontWeight: 300, color: 'var(--ink-mute)',
                      lineHeight: 1 }}>{before}</span>
        <span style={{ fontSize: 14, color: 'var(--ink-faint)' }}>→</span>
        <span className="display" style={{ fontSize: 36, fontWeight: 300,
                      color: bad ? 'var(--accent)' : 'var(--success)',
                      lineHeight: 1 }}>{after}</span>
        <span style={{ flex: 1 }}/>
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 4,
                       fontSize: 12, color: bad ? 'var(--accent)' : 'var(--success)',
                       fontWeight: 500 }}>
          <span style={{ fontSize: 14 }}>{dir === "down" ? "↓" : "↑"}</span>
          <span className="mono">{delta}</span>
        </div>
      </div>
    </div>
  );
}

window.ObsImpact = ObsImpact;
window.ObsNegativeAlert = ObsNegativeAlert;

// app/src/routes/(observatory)/impact/+page.svelte
<script lang="ts">
  import { PageHeader, EmptyState, Eyebrow } from '$lib/components';
  import { formatDeltaPct, type ImpactRow } from './aggregate.js';

  let { data } = $props();

  // Flatten buckets into a single ordered feed for the aside list.
  // Order — negative first (loudest to act on), then positive, neutral,
  // pending. Within each bucket the buckets already sort by |ftrDelta|.
  const flat = $derived<ImpactRow[]>([
    ...data.buckets.negative,
    ...data.buckets.positive,
    ...data.buckets.neutral,
    ...data.buckets.pending,
  ]);

  // The picked-row id — null until the user clicks a row, at which point
  // it's honoured. The `open` derived falls back to the first row when
  // `openId` is null OR the picked row is no longer in the flat list.
  let openId = $state<string | null>(null);
  const open = $derived(
    flat.find((r) => r.id === openId) ?? flat[0],
  );
  const openVm = $derived(open ? meta(open.verdict) : null);

  const VERDICT_META = {
    positive: { glyph: '好', tone: 'success', label: 'positive impact' },
    neutral:  { glyph: '並', tone: 'ink',     label: 'no measurable effect' },
    negative: { glyph: '悪', tone: 'warning', label: 'negative impact' },
    pending:  { glyph: '待', tone: 'ink',     label: 'measurement pending' },
  } as const;

  function meta(v: ImpactRow['verdict']) {
    return VERDICT_META[v] ?? VERDICT_META.pending;
  }

  function pct(v: number | null): string {
    if (v == null) return '—';
    return `${Math.round(v * 100)}%`;
  }

  function toneClass(tone: string, kind: 'text' | 'bg' | 'border' = 'text'): string {
    const prefix = kind === 'text' ? 'text' : kind === 'bg' ? 'bg' : 'border';
    if (tone === 'success') return `${prefix}-success`;
    if (tone === 'warning') return `${prefix}-warning`;
    return `${prefix}-ink-mute`;
  }
</script>

<div class="flex flex-col h-full" data-impact-total={data.total}>
  <!-- Header — kanji + eyebrow + title + description + 4 verdict counts -->
  <div class="flex items-center gap-5 pt-5 pb-4 px-6 border-b border-paper-edge">
    <span class="kanji text-[40px] text-accent leading-none">果</span>
    <div class="flex-1 min-w-0">
      <p class="m-0 mb-1"><Eyebrow>Observatory · Change impact</Eyebrow></p>
      <h1 class="display text-[22px] font-normal m-0">Did sensei's advice actually work?</h1>
      <p class="text-[13px] text-ink-mute mt-1 mb-0 max-w-[720px] leading-relaxed">
        Each accepted recommendation gets a measurement window. FTR baseline
        vs current is compared. The MOE panel writes the reasoning.
      </p>
    </div>
    <div class="flex gap-5 pl-5 border-l border-paper-edge">
      <div class="text-center">
        <div class="font-mono text-[17px] font-light text-success">{data.buckets.positive.length}</div>
        <div class="text-xs uppercase tracking-wider text-ink-faint mt-1">positive</div>
      </div>
      <div class="text-center">
        <div class="font-mono text-[17px] font-light text-ink">{data.buckets.neutral.length}</div>
        <div class="text-xs uppercase tracking-wider text-ink-faint mt-1">neutral</div>
      </div>
      <div class="text-center">
        <div class="font-mono text-[17px] font-light text-warning">{data.buckets.negative.length}</div>
        <div class="text-xs uppercase tracking-wider text-ink-faint mt-1">negative</div>
      </div>
      <div class="text-center">
        <div class="font-mono text-[17px] font-light text-ink-soft">{data.buckets.pending.length}</div>
        <div class="text-xs uppercase tracking-wider text-ink-faint mt-1">pending</div>
      </div>
    </div>
  </div>

  {#if data.total === 0 || !open}
    <div class="p-6">
      <EmptyState
        kanji="果"
        title="no measurements yet"
        description="Accepted recommendations show up here once the analyzer's MeasureVerdicts pass has enough post-acceptance sessions (typically ≥3 sessions across ≥3 days)."
      />
    </div>
  {:else}
    <!-- Two columns: aside list + main detail -->
    <div class="grid grid-cols-[300px_1fr] min-h-0 flex-1" data-impact-body>
      <aside class="border-r border-paper-edge overflow-auto py-2">
        {#each flat as r (r.id)}
          {@const vm = meta(r.verdict)}
          {@const isOpen = open.id === r.id}
          <button
            type="button"
            class="w-full text-left py-3 px-4 cursor-pointer bg-transparent border-none text-inherit block"
            class:bg-paper-mute={isOpen}
            data-impact-row={r.id}
            data-impact-bucket={r.verdict}
            style={isOpen ? `border-left: 2px solid var(${vm.tone === 'success' ? '--success' : vm.tone === 'warning' ? '--warning' : '--ink-mute'});` : 'border-left: 2px solid transparent;'}
            onclick={() => (openId = r.id)}
          >
            <div class="flex items-center gap-2">
              <span class="kanji text-[13px] {toneClass(vm.tone)}">{vm.glyph}</span>
              <span class="text-xs uppercase tracking-wider {toneClass(vm.tone)}">{r.verdict}</span>
              <span class="flex-1"></span>
              <span
                class="font-mono text-xs"
                class:text-success={r.ftrDelta != null && r.ftrDelta > 0}
                class:text-warning={r.ftrDelta != null && r.ftrDelta < 0}
                class:text-ink-mute={r.ftrDelta == null || r.ftrDelta === 0}
                data-ftr-delta
              >{formatDeltaPct(r.ftrDelta)}</span>
            </div>
            <div class="text-[13px] mt-1 leading-snug font-medium truncate"
                 class:text-ink={isOpen}
                 class:text-ink-mute={!isOpen}>{r.title}</div>
            <div class="font-mono text-xs text-ink-faint mt-1 truncate">{r.projectName}</div>
          </button>
        {/each}
      </aside>

      <main class="overflow-auto pt-5 pb-6 px-7">
        <!-- Eyebrow line — project · verdict metadata -->
        <div class="flex items-center gap-3 text-xs uppercase tracking-wider text-ink-soft mb-3">
          <span class="font-mono normal-case tracking-normal">{open.projectName}</span>
          <span class="text-ink-faint">·</span>
          <span>{open.status}</span>
        </div>

        <h2 class="display text-[28px] font-light mt-0 mb-4 leading-tight tracking-tight text-ink">
          {open.title}
        </h2>

        <!-- Verdict pill -->
        {#if openVm}
          <div class="flex items-center gap-3 mb-5">
            <div
              class="inline-flex items-center gap-2 py-1 px-3 rounded-full border"
              class:bg-success-soft={openVm.tone === 'success'}
              class:border-success={openVm.tone === 'success'}
              class:bg-warning-soft={openVm.tone === 'warning'}
              class:border-warning={openVm.tone === 'warning'}
              class:bg-paper-mute={openVm.tone === 'ink'}
              class:border-paper-edge={openVm.tone === 'ink'}
            >
              <span class="kanji text-[13px] {toneClass(openVm.tone)}">{openVm.glyph}</span>
              <span class="text-xs uppercase tracking-wider font-medium {toneClass(openVm.tone)}">
                {openVm.label}
              </span>
            </div>
          </div>
        {/if}

        <!-- Before / after FTR strip -->
        <div class="grid grid-cols-4 gap-[1px] bg-paper-edge rounded overflow-hidden mb-5">
          <div class="bg-paper-mute py-3 px-4">
            <div class="text-xs uppercase tracking-wider text-ink-faint mb-1">First-Try-Right</div>
            <div class="font-mono text-sm text-ink-mute">{pct(open.baselineFtr)}</div>
            <div class="font-mono text-lg text-ink">{pct(open.currentFtr)}</div>
            <div
              class="font-mono text-xs mt-1"
              class:text-success={open.ftrDelta != null && open.ftrDelta > 0}
              class:text-warning={open.ftrDelta != null && open.ftrDelta < 0}
              class:text-ink-mute={open.ftrDelta == null || open.ftrDelta === 0}
            >
              {formatDeltaPct(open.ftrDelta)}
            </div>
          </div>
          <div class="bg-paper-mute py-3 px-4">
            <div class="text-xs uppercase tracking-wider text-ink-faint mb-1">Status</div>
            <div class="font-mono text-sm text-ink mt-3">{open.status}</div>
          </div>
          <div class="bg-paper-mute py-3 px-4">
            <div class="text-xs uppercase tracking-wider text-ink-faint mb-1">Verdict</div>
            <div class="font-mono text-sm mt-3 {toneClass(openVm?.tone ?? 'ink')}">{open.verdict}</div>
          </div>
          <div class="bg-paper-mute py-3 px-4">
            <div class="text-xs uppercase tracking-wider text-ink-faint mb-1">Project</div>
            <div class="font-mono text-sm text-ink mt-3 truncate">{open.projectName}</div>
          </div>
        </div>

        <!-- MOE reasoning — full panel shape when the daemon carries one -->
        {#if open.reasoning}
          {@const models = open.reasoning.models ?? []}
          <div
            class="py-4 px-5 mb-5 rounded bg-paper-mute border border-paper-edge"
            style={`border-left: 2px solid var(${openVm?.tone === 'success' ? '--success' : openVm?.tone === 'warning' ? '--warning' : '--ink-mute'});`}
            data-testid="impact-moe-panel"
          >
            <!-- Header row: 議 + eyebrow + consensus summary -->
            <div class="flex items-center gap-2 mb-2">
              <span class="kanji text-[13px] text-accent">議</span>
              <span class="text-xs uppercase tracking-wider text-ink-soft">MOE panel reasoning</span>
              <span class="flex-1"></span>
              {#if open.reasoning.consensus}
                <span class="font-mono text-xs text-ink-soft" data-testid="impact-moe-consensus">
                  {open.reasoning.consensus}
                </span>
              {/if}
            </div>

            <!-- Headline — 1 line, the sharpest sentence -->
            {#if open.reasoning.headline}
              <div class="text-[13px] text-ink font-medium leading-snug mb-2" data-testid="impact-moe-headline">
                {open.reasoning.headline}
              </div>
            {/if}

            <!-- Body — 2-3 sentence explanation -->
            {#if open.reasoning.body}
              <p class="text-[13px] text-ink-mute leading-relaxed m-0 mb-3" data-testid="impact-moe-body">
                {open.reasoning.body}
              </p>
            {/if}

            <!-- Per-model breakdown — name + role chip + note -->
            {#if models.length > 0}
              <div class="flex flex-col gap-1 pt-3 border-t border-paper-edge" data-testid="impact-moe-models">
                {#each models as m (m.name)}
                  <div class="grid grid-cols-[120px_14px_1fr] gap-2 items-start" data-testid={`impact-moe-model-${m.name}`}>
                    <span class="font-mono text-xs text-ink truncate">{m.name}</span>
                    <span class="kanji text-[13px] text-accent mt-1">議</span>
                    <div>
                      <span class="text-xs uppercase tracking-wider text-ink-soft">{m.role}</span>
                      <p class="text-xs text-ink-mute leading-relaxed m-0 mt-0.5">{m.note}</p>
                    </div>
                  </div>
                {/each}
              </div>
            {/if}

            <!-- Suggested revision — only surfaced on a negative verdict -->
            {#if open.reasoning.suggestedRevision}
              <div class="mt-3 py-2 px-3 rounded bg-paper border border-paper-edge" data-testid="impact-moe-revision">
                <div class="text-xs uppercase tracking-wider text-accent mb-1">Suggested revision</div>
                <p class="text-xs text-ink-mute leading-relaxed m-0">{open.reasoning.suggestedRevision}</p>
              </div>
            {/if}
          </div>
        {:else}
          <p class="text-sm text-ink-soft italic">
            No MOE reasoning trace captured for this verdict yet.
          </p>
        {/if}
      </main>
    </div>
  {/if}
</div>
