// docs/mockups/Sensei/hq/torii-seiki.jsx
// ─────────────────────────────────────────────────────────────────
// TORII + SEIKI — product page (Sensei HQ site)
// Two clients for an org's models, both built on Gateway:
// Torii (member workspace) and Seiki (admin portal).
// Same Zen-Sumi world as the HQ site: washi paper, sumi ink,
// Fraunces display, kanji marks, hairlines, one rationed accent.
// ─────────────────────────────────────────────────────────────────

const { useEffect: hE } = React;
const { TweaksPanel, useTweaks, TweakSection, TweakToggle, TweakRadio } = window;

const MAXW = 1120;

const ACCENT = {
  light: { torii: 'oklch(0.560 0.140 15)', seiki: 'oklch(0.560 0.130 255)' },
  dark:  { torii: 'oklch(0.700 0.140 15)', seiki: 'oklch(0.700 0.130 255)' },
};

const GATEWAY_URL = 'https://gateway.sensei-hq.com';

const CLIENTS = [
  {
    id: 'torii', kanji: '門', gloss: 'Mon · the gate',
    name: 'Torii', category: 'Desktop · Member workspace',
    tagline: 'The gate your team walks through.',
    blurb: 'Everything a member needs and nothing they don’t. Ask a model, keep a library, try things in the playground — and always see where the answer actually ran.',
    surfaces: ['Workspace', 'Ask', 'Library', 'Playground', 'Activity', 'Settings'],
    meta: ['macOS · Windows · Linux', 'Tauri', 'Works offline'],
    status: 'Beta',
  },
  {
    id: 'seiki', kanji: '社', gloss: 'Sha · the sanctuary',
    name: 'Seiki', category: 'Web · Governance plane',
    tagline: 'The sanctuary behind it.',
    blurb: 'The quiet room where the rules are kept. Every request, every provider, every fallback chain and every budget — set once, cascading down your org, without standing over anyone’s shoulder.',
    surfaces: ['Overview', 'Requests & audit', 'Organization', 'Models', 'Routing', 'Connections', 'Governance', 'Budgets'],
    meta: ['Self-hosted', 'SSO · SCIM', 'Full audit trail'],
    status: 'Beta',
  },
];

const CAPABILITIES = [
  { kanji: '路', title: 'Fallback chains', text: 'Order your models once — primary, then the next, then the local one. Gateway walks the chain when a provider stalls, and Seiki shows you how often it had to.' },
  { kanji: '繋', title: 'Connections', text: 'Bring your own keys for every provider and router. Strategos holds the credentials; your apps hold one address.' },
  { kanji: '具', title: 'MCP & tools', text: 'Register MCP servers — stdio on the desktop, http for shared ones — and allow-list tools per role and space.' },
  { kanji: '鍵', title: 'Programmatic access', text: 'Scoped keys turn the same gateway into an endpoint your own services can call, with usage attributed back to a team.' },
  { kanji: '階', title: 'Hierarchy & budgets', text: 'Org, department, team, person — your real structure. Permissions follow it, and so do spend caps, cascading downward.' },
  { kanji: '器', title: 'Devices & offline', text: 'Local models run on the machine in front of you. When the gateway is unreachable, work continues and syncs later.' },
];

const PLANES = [
  { label: 'On your device', kanji: '手', text: 'Local models, local context, nothing leaves the machine. Marked as such on every answer.' },
  { label: 'Via the gateway', kanji: '関', text: 'Routed, logged and budgeted through your own deployment — in the region you chose.' },
];

// ─── Primitives ──────────────────────────────────────────────────────
function Enso({ size = 26, stroke = 'var(--accent)' }) {
  return (
    <span className="block shrink-0" aria-hidden="true"
 style={{ width: size, height: size, background: stroke,
 WebkitMaskImage: 'url(uploads/sensei.svg?v=3)', maskImage: 'url(uploads/sensei.svg?v=3)',
 WebkitMaskSize: 'contain', maskSize: 'contain',
 WebkitMaskRepeat: 'no-repeat', maskRepeat: 'no-repeat',
 WebkitMaskPosition: 'center', maskPosition: 'center' }} />
  );
}

function Eyebrow({ children, style }) {
  return <div className="zs-eyebrow" style={style}>{children}</div>;
}

function MetaChips({ meta }) {
  return (
    <div className="gap-2 flex flex-wrap">
      {meta.map((m) => (
        <span key={m} className="mono text-ink-mute border border-paper-edge rounded-sm whitespace-nowrap"
 style={{ fontSize: 11, padding: '2px 7px' }}>{m}</span>
      ))}
    </div>
  );
}

function SectionHead({ kanji, eyebrow, title, sub }) {
  return (
    <div className="mb-12">
      <div className="gap-3 mb-4 flex items-baseline">
        <span className="kanji text-accent" style={{ fontSize: 28, lineHeight: 1 }}>{kanji}</span>
        <Eyebrow>{eyebrow}</Eyebrow>
      </div>
      <h2 className="display text-ink m-0 font-light"
 style={{ fontSize: 40, lineHeight: 1.15, letterSpacing: '-0.022em', maxWidth: 720 }}>{title}</h2>
      {sub && <p className="text-ink-soft mt-4 m-0" style={{ fontSize: 17, lineHeight: 1.6, maxWidth: 560 }}>{sub}</p>}
    </div>
  );
}

// ─── Nav ─────────────────────────────────────────────────────────────
function Nav() {
  const links = [['#clients', 'The pair'], ['#planes', 'Two planes'], ['#capabilities', 'Capabilities'], ['#gateway', 'Gateway']];
  return (
    <div className="sticky" style={{ top: 0, zIndex: 50,
 background: 'color-mix(in oklch, var(--paper) 80%, transparent)',
 backdropFilter: 'blur(14px) saturate(150%)', WebkitBackdropFilter: 'blur(14px) saturate(150%)',
 WebkitMaskImage: 'linear-gradient(to bottom, #000 72%, transparent)',
 maskImage: 'linear-gradient(to bottom, #000 72%, transparent)', paddingBottom: 6 }}>
      <nav style={{ maxWidth: MAXW }} className="mx-auto px-12 py-4 flex items-center justify-between">
        <a href="Sensei HQ.html" className="gap-3 flex items-center">
          <Enso size={26} stroke="var(--accent)" />
          <span className="gap-2 flex items-baseline">
            <span className="display text-ink" style={{ fontSize: 17, letterSpacing: '-0.01em' }}>Torii · Seiki</span>
            <span className="mono text-ink-mute" style={{ fontSize: 11, letterSpacing: '0.08em' }}>SENSEI HQ</span>
          </span>
        </a>
        <div className="gap-8 flex items-center">
          {links.map(([href, label]) => (
            <a key={href} href={href} className="text-ink-soft text-sm" style={{ transition: 'color .15s' }}
               onMouseEnter={(e) => e.currentTarget.style.color = 'var(--ink)'}
               onMouseLeave={(e) => e.currentTarget.style.color = 'var(--ink-soft)'}>{label}</a>
          ))}
          <a href="#contact" className="zs-btn zs-btn-primary zs-btn-sm" style={{ marginLeft: 4 }}>Request access</a>
        </div>
      </nav>
    </div>
  );
}

// ─── Hero ────────────────────────────────────────────────────────────
function Hero() {
  return (
    <header id="top" style={{ maxWidth: MAXW }} className="mx-auto px-12 pt-12 pb-24">
      <div style={{ gridTemplateColumns: '1.55fr 1fr' }} className="gap-16 grid items-start">
        <div>
          <div className="gap-3 mb-6 flex items-baseline">
            <span className="kanji text-accent" style={{ fontSize: 44, lineHeight: 1 }}>門</span>
            <Eyebrow>Torii · Seiki — the gate and what stands behind it</Eyebrow>
          </div>
          <h1 className="display text-ink m-0 font-light"
 style={{ fontSize: 56, lineHeight: 1.08, letterSpacing: '-0.025em', maxWidth: 640 }}>
The gate, and the sanctuary behind it.
          </h1>
          <p className="text-ink-soft mt-6 m-0" style={{ fontSize: 17, lineHeight: 1.6, maxWidth: 540 }}>
            Torii is the gate your team walks through to reach your models. Seiki is the
            governance plane behind it — routing, budgets, audit. Both stand on Gateway,
            our Rust library for fallback chains and budget control.
          </p>
          <div className="gap-3 mt-8 flex items-center flex-wrap">
            <a href="#contact" className="zs-btn zs-btn-primary zs-btn-lg">
              <span className="kanji text-on-primary" style={{ fontSize: 15, lineHeight: 1 }}>入</span>
              Request access
            </a>
            <a href="#clients" className="text-ink-soft text-sm">Meet Torii and Seiki ↓</a>
          </div>
          <div className="gap-4 mt-12 flex flex-wrap">
            {['Self-hosted', 'Bring your own keys', 'Built on Gateway'].map((m) => (
              <span key={m} className="mono text-ink-mute" style={{ fontSize: 11 }}>{m}</span>
            ))}
          </div>
        </div>

        <aside className="border border-paper-edge rounded-lg bg-paper-soft overflow-hidden">
          <div className="px-6 py-4 border-b border-paper-edge flex items-center justify-between">
            <Eyebrow>The pair</Eyebrow>
            <span className="mono text-ink-faint" style={{ fontSize: 11 }}>02</span>
          </div>
          <div className="divide-y">
            {CLIENTS.map((c) => (
              <a key={c.id} href={'#' + c.id}
 style={{ gridTemplateColumns: 'auto 1fr auto', '--accent': `var(--acc-${c.id})`, transition: 'background .15s' }}
 className="gap-4 px-6 py-4 grid items-center"
 onMouseEnter={(e) => e.currentTarget.style.background = 'var(--paper-mute)'}
 onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}>
                <span className="kanji text-accent text-center" style={{ fontSize: 26, lineHeight: 1, width: 30 }}>{c.kanji}</span>
                <span>
                  <span className="display text-ink block" style={{ fontSize: 15 }}>{c.name}</span>
                  <span className="text-ink-mute text-xs">{c.category}</span>
                </span>
                <span className="zs-dot bg-accent" />
              </a>
            ))}
          </div>
          <div className="px-6 py-4 border-t border-paper-edge">
            <p className="text-ink-mute m-0" style={{ fontSize: 13, lineHeight: 1.6 }}>
Pass through the gate and the rules are already in force. That is the point of the pair.
            </p>
          </div>
        </aside>
      </div>
    </header>
  );
}

// ─── Two planes ──────────────────────────────────────────────────────
function Planes() {
  return (
    <section id="planes" className="sec border-t border-paper-edge">
      <div style={{ maxWidth: MAXW }} className="mx-auto px-12">
        <SectionHead kanji="分" eyebrow="Bun · to divide" title="Every answer knows where it ran."
          sub="The split execution plane is not a setting buried in preferences — it is written on the response, every time." />
        <div style={{ gridTemplateColumns: '1fr 1fr' }} className="gap-6 grid">
          {PLANES.map((p) => (
            <div key={p.label} className="zs-card">
              <div className="gap-3 mb-4 flex items-center">
                <span className="kanji text-accent" style={{ fontSize: 22, lineHeight: 1 }}>{p.kanji}</span>
                <span className="mono text-ink border border-paper-edge rounded-full" style={{ fontSize: 11, padding: '3px 10px' }}>{p.label}</span>
              </div>
              <p className="text-ink-soft m-0" style={{ fontSize: 15, lineHeight: 1.65 }}>{p.text}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Clients ─────────────────────────────────────────────────────────
function ClientCard({ c, flip }) {
  const panel = (
    <div className="flex items-center justify-center bg-paper-mute relative overflow-hidden"
 style={{ minHeight: 340, borderLeft: flip ? 'none' : 'var(--hairline)', borderRight: flip ? 'var(--hairline)' : 'none' }}>
      <span className="kanji text-accent" style={{ fontSize: 220, lineHeight: 1, opacity: 0.92 }}>{c.kanji}</span>
      <span className="mono absolute text-ink-faint" style={{ bottom: 18, right: 20, fontSize: 11, letterSpacing: '0.14em' }}>{c.gloss}</span>
    </div>
  );
  const body = (
    <div className="p-12">
      <div className="mb-6 flex items-center justify-between">
        <span className="mono text-ink-faint" style={{ fontSize: 13 }}>{c.id === 'torii' ? '01' : '02'}</span>
        <span className="zs-badge zs-badge-warning" style={{ whiteSpace: 'nowrap' }}>{c.status}</span>
      </div>
      <div className="gap-3 mb-2 flex items-baseline flex-wrap">
        <span className="display text-ink font-normal" style={{ fontSize: 28, letterSpacing: '-0.02em' }}>{c.name}</span>
        <span className="zs-eyebrow">{c.category}</span>
      </div>
      <p className="display text-ink m-0 font-light" style={{ fontSize: 22, letterSpacing: '-0.015em', lineHeight: 1.3 }}>{c.tagline}</p>
      <p className="text-ink-soft mt-3" style={{ fontSize: 15, lineHeight: 1.65, maxWidth: 460 }}>{c.blurb}</p>
      <div className="gap-2 mt-6 mb-8 flex flex-wrap">
        {c.surfaces.map((s) => (
          <span key={s} className="text-ink-soft text-sm border border-paper-edge rounded-full whitespace-nowrap"
 style={{ padding: '4px 12px' }}>{s}</span>
        ))}
      </div>
      <MetaChips meta={c.meta} />
    </div>
  );
  return (
    <div id={c.id} className="zs-card-flush grid overflow-hidden"
 style={{ gridTemplateColumns: flip ? '1fr 1.3fr' : '1.3fr 1fr', '--accent': `var(--acc-${c.id})` }}>
      {flip ? panel : body}
      {flip ? body : panel}
    </div>
  );
}

function Clients() {
  return (
    <section id="clients" className="sec border-t border-paper-edge">
      <div style={{ maxWidth: MAXW }} className="mx-auto px-12">
        <SectionHead kanji="二" eyebrow="Ni · two" title="Two tools, one temperament."
          sub="Torii is what your team opens in the morning. Seiki is where you go when you need to know why — and to change it." />
        <div className="gap-8 flex flex-col">
          {CLIENTS.map((c, i) => <ClientCard key={c.id} c={c} flip={i % 2 === 1} />)}
        </div>
      </div>
    </section>
  );
}

// ─── Capabilities ────────────────────────────────────────────────────
function Capabilities() {
  return (
    <section id="capabilities" className="sec border-t border-paper-edge">
      <div style={{ maxWidth: MAXW }} className="mx-auto px-12">
        <SectionHead kanji="具" eyebrow="Gu · the instruments" title="What the pair is made of." />
        <div style={{ gridTemplateColumns: 'repeat(3, 1fr)' }} className="gap-x-12 gap-y-12 grid">
          {CAPABILITIES.map((c) => (
            <div key={c.title}>
              <span className="kanji text-accent block" style={{ fontSize: 32, lineHeight: 1, marginBottom: 16 }}>{c.kanji}</span>
              <h3 className="display text-ink m-0 font-normal" style={{ fontSize: 17, letterSpacing: '-0.01em' }}>{c.title}</h3>
              <p className="text-ink-soft mt-2 m-0" style={{ fontSize: 13, lineHeight: 1.65 }}>{c.text}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Privacy ─────────────────────────────────────────────────────────
function Privacy() {
  return (
    <section id="privacy" className="sec border-t border-paper-edge">
      <div style={{ maxWidth: MAXW }} className="mx-auto px-12">
        <div style={{ gridTemplateColumns: '1fr 1fr' }} className="gap-16 grid items-start">
          <div>
            <SectionHead kanji="蔵" eyebrow="Zō · to keep" title="Your prompts stay in your building." />
            <p className="text-ink-soft m-0" style={{ fontSize: 15, lineHeight: 1.7, maxWidth: 460 }}>
              Both clients run on your own infrastructure. There is no Sensei HQ account, no
              telemetry back to us, and no copy of your traffic anywhere we can read it.
              You hold the provider keys; you choose the region; you can export or delete
              the whole audit log whenever you like.
            </p>
          </div>
          <div className="zs-card">
            <Eyebrow style={{ marginBottom: 16 }}>What leaves your network</Eyebrow>
            <div className="flex flex-col">
              {[
                ['Prompts and responses', 'Only to the provider you routed them to.'],
                ['Audit log', 'Never. It lives in your database.'],
                ['Usage telemetry', 'Never. There is none to send.'],
                ['Licence check', 'Once, at install. Offline after that.'],
              ].map(([k, v], i, arr) => (
                <div key={k} className="py-3 flex items-baseline justify-between gap-6"
 style={{ borderBottom: i === arr.length - 1 ? 'none' : 'var(--hairline)' }}>
                  <span className="text-ink text-sm">{k}</span>
                  <span className="text-ink-mute text-sm" style={{ textAlign: 'right', maxWidth: 240 }}>{v}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── Gateway ─────────────────────────────────────────────────────────
function Gateway() {
  return (
    <section id="gateway" className="sec border-t border-paper-edge">
      <div style={{ maxWidth: MAXW }} className="mx-auto px-12">
        <div style={{ gridTemplateColumns: '1fr 1fr' }} className="gap-16 grid items-center">
          <div>
            <SectionHead kanji="基" eyebrow="Ki · the foundation" title="Both are built on Gateway." />
            <p className="text-ink-soft m-0" style={{ fontSize: 15, lineHeight: 1.7, maxWidth: 460 }}>
              Gateway is our Rust library for talking to model providers: fallback chains,
              budget control, and one interface across every vendor you use. Torii and Seiki
              are what it looks like with a face on it — but the library stands alone, and
              you can build your own client on it.
            </p>
            <a href={GATEWAY_URL} className="zs-btn zs-btn-secondary mt-6">gateway.sensei-hq.com →</a>
          </div>
          <div className="zs-card">
            <Eyebrow style={{ marginBottom: 16 }}>What Gateway handles</Eyebrow>
            <div className="flex flex-col">
              {[
                ['Fallback chains', 'Primary, secondary, local — in order, on failure.'],
                ['Budget control', 'Hard ceilings per key, per team, per period.'],
                ['One interface', 'Every provider behind a single Rust API.'],
                ['Rust, embedded', 'A library in your service, not another hop.'],
              ].map(([k, v], i, arr) => (
                <div key={k} className="py-3 flex items-baseline justify-between gap-6"
 style={{ borderBottom: i === arr.length - 1 ? 'none' : 'var(--hairline)' }}>
                  <span className="text-ink text-sm">{k}</span>
                  <span className="text-ink-mute text-sm" style={{ textAlign: 'right', maxWidth: 240 }}>{v}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── Contact ─────────────────────────────────────────────────────────
function Contact() {
  return (
    <section id="contact" className="sec border-t border-paper-edge">
      <div style={{ maxWidth: 720 }} className="mx-auto px-12 text-center">
        <span className="kanji text-accent block" style={{ fontSize: 40, lineHeight: 1, marginBottom: 20 }}>入</span>
        <h2 className="display text-ink m-0 font-light" style={{ fontSize: 40, lineHeight: 1.15, letterSpacing: '-0.022em' }}>
          Torii and Seiki are in private beta.
        </h2>
        <p className="text-ink-soft mt-4 m-0" style={{ fontSize: 17, lineHeight: 1.6 }}>
          Tell us how your organization works and we will tell you honestly whether the gate fits yet.
        </p>
        <div className="gap-3 mt-8 flex items-center justify-center flex-wrap">
          <a href="mailto:hi@sensei-hq.com" className="zs-btn zs-btn-primary zs-btn-lg">
            <span className="kanji text-on-primary" style={{ fontSize: 15, lineHeight: 1 }}>文</span>
            Request access
          </a>
          <a href="Sensei HQ.html" className="zs-btn zs-btn-secondary zs-btn-lg">See the whole workshop</a>
        </div>
        <a href="mailto:hi@sensei-hq.com" className="mono text-ink-mute mt-4 inline-block whitespace-nowrap"
 style={{ fontSize: 13, letterSpacing: '0.02em' }}>hi@sensei-hq.com</a>
      </div>
    </section>
  );
}

function Footer() {
  return (
    <footer className="border-t border-paper-edge">
      <div style={{ maxWidth: MAXW }} className="mx-auto px-12 py-16 flex items-center justify-between flex-wrap" >
        <a href="Sensei HQ.html" className="gap-3 flex items-center">
          <Enso size={24} stroke="var(--accent)" />
          <span className="gap-2 flex items-baseline">
            <span className="display text-ink" style={{ fontSize: 15 }}>Sensei</span>
            <span className="mono text-ink-mute" style={{ fontSize: 11, letterSpacing: '0.08em' }}>HQ</span>
          </span>
        </a>
        <span className="mono text-ink-faint" style={{ fontSize: 11 }}>門 · Torii · Seiki · built on Gateway</span>
      </div>
    </footer>
  );
}

// ─── Root ────────────────────────────────────────────────────────────
const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "dark": false,
  "density": "airy",
  "accentMode": "distinct"
}/*EDITMODE-END*/;

function ToriiSeikiPage() {
  const [t, setTweak] = useTweaks(TWEAK_DEFAULTS);

  hE(() => {
    document.documentElement.setAttribute('data-theme', t.dark ? 'dark' : 'light');
  }, [t.dark]);

  const set = ACCENT[t.dark ? 'dark' : 'light'];
  const accentVars = { '--accent': set.torii };
  ['torii', 'seiki'].forEach((id) => {
    accentVars[`--acc-${id}`] = t.accentMode === 'distinct' ? set[id] : set.torii;
  });

  const secPad = t.density === 'compact' ? 56 : 92;

  return (
    <div className="sensei min-h-full bg-paper relative" style={accentVars}>
      <style>{`
        .sensei .sec{ padding-top:${secPad}px; padding-bottom:${secPad}px; }
        .sensei .display, .sensei .zs-display, .sensei .zs-h1, .sensei .zs-h2,
        .sensei .zs-h3, .sensei h1, .sensei h2, .sensei h3,
        .sensei .zs-hero, .sensei .zs-display-lg{
          font-optical-sizing:none;
          font-variation-settings:"opsz" 16;
          font-feature-settings:"ss01" 0;
        }
      `}</style>
      <Nav />
      <Hero />
      <Planes />
      <Clients />
      <Capabilities />
      <Privacy />
      <Gateway />
      <Contact />
      <Footer />

      <TweaksPanel title="Tweaks">
        <TweakSection label="Theme" />
        <TweakToggle label="Dark mode" value={t.dark} onChange={(v) => setTweak('dark', v)} />
        <TweakSection label="Layout" />
        <TweakRadio label="Density" value={t.density} options={['airy', 'compact']}
                    onChange={(v) => setTweak('density', v)} />
        <TweakSection label="Client color" />
        <TweakRadio label="Accents" value={t.accentMode}
                    options={[{ value: 'distinct', label: 'Distinct' }, { value: 'unified', label: 'Unified' }]}
                    onChange={(v) => setTweak('accentMode', v)} />
      </TweaksPanel>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById('root')).render(<ToriiSeikiPage />);

// website/src/routes/torii-seiki/+page.svelte
<script lang="ts">
  import { base } from '$app/paths';
  import {
    CLIENTS,
    PLANES,
    CAPABILITIES,
    PRIVACY_ROWS,
    GATEWAY_ROWS,
    GATEWAY_URL,
    TS_NAV_LINKS,
  } from '$lib/torii-seiki-data.js';
</script>

<svelte:head>
  <title>Torii · Seiki — the gate and the governance plane · Sensei HQ</title>
  <meta
    name="description"
    content="Torii is the desktop client your team walks through to reach your models; Seiki is the self-hosted governance plane behind it — routing, budgets, audit. Both built on Gateway." />
</svelte:head>

<!-- ── Nav ───────────────────────────────────────────────────────────── -->
<div class="ts-nav-wrap sticky top-0 z-50">
  <nav class="ts-inner mx-auto px-7 py-4 flex items-center justify-between">
    <a href="{base}/" class="flex items-center gap-3 no-underline">
      <span class="i-brand:sensei-hq text-primary block flex-shrink-0" style="width:26px;height:26px" aria-hidden="true"></span>
      <span class="flex items-baseline gap-2">
        <span class="display text-ink text-lg" style="letter-spacing:-0.01em">Torii · Seiki</span>
        <span class="mono text-ink-mute text-xs" style="letter-spacing:0.08em">SENSEI HQ</span>
      </span>
    </a>
    <div class="flex items-center gap-8">
      {#each TS_NAV_LINKS as [href, label] (href)}
        <a {href} class="ts-nav-link text-ink-soft text-sm no-underline">{label}</a>
      {/each}
      <a href="#contact" class="zs-btn zs-btn-primary zs-btn-sm" style="margin-left:4px">Request access</a>
    </div>
  </nav>
</div>

<!-- ── Hero ──────────────────────────────────────────────────────────── -->
<header id="top" class="ts-inner mx-auto px-7 pt-12 pb-24">
  <div class="ts-hero-grid gap-16">
    <div>
      <div class="flex items-baseline gap-3 mb-6">
        <span class="kanji text-primary" style="font-size:44px;line-height:1">門</span>
        <span class="mono text-ink-mute text-xs" style="letter-spacing:0.12em;text-transform:uppercase">Torii · Seiki — the gate and what stands behind it</span>
      </div>
      <h1 class="display text-ink m-0" style="font-size:56px;font-weight:300;line-height:1.08;letter-spacing:-0.025em;max-width:640px">
        The gate, and the sanctuary behind it.
      </h1>
      <p class="text-ink-soft mt-6 m-0" style="font-size:17px;line-height:1.6;max-width:540px">
        Torii is the gate your team walks through to reach your models. Seiki is the
        governance plane behind it — routing, budgets, audit. Both stand on Gateway,
        our Rust library for fallback chains and budget control.
      </p>
      <div class="flex items-center flex-wrap gap-3 mt-8">
        <a href="mailto:hi@sensei-hq.com" class="zs-btn zs-btn-primary zs-btn-lg">
          <span class="kanji text-on-primary" style="font-size:15px;line-height:1">入</span>
          Request access
        </a>
        <a href="#clients" class="text-ink-soft text-sm no-underline">Meet Torii and Seiki ↓</a>
      </div>
      <div class="flex flex-wrap gap-4 mt-12">
        {#each ['Self-hosted', 'Bring your own keys', 'Built on Gateway'] as m (m)}
          <span class="mono text-ink-mute text-xs">{m}</span>
        {/each}
      </div>
    </div>

    <aside class="border border-paper-edge rounded-lg bg-paper-soft" style="overflow:hidden">
      <div class="px-6 py-4 border-b border-paper-edge flex items-center justify-between">
        <span class="mono text-ink-mute text-xs" style="letter-spacing:0.12em;text-transform:uppercase">The pair</span>
        <span class="mono text-ink-faint text-xs">02</span>
      </div>
      <div>
        {#each CLIENTS as c (c.id)}
          <a href="#{c.id}" class="ts-pair-row gap-4 px-6 py-4 no-underline text-{c.id}">
            <span class="kanji text-{c.id} text-center" style="font-size:26px;line-height:1;width:30px">{c.kanji}</span>
            <span>
              <span class="display text-ink block text-base">{c.name}</span>
              <span class="text-ink-mute text-xs">{c.category}</span>
            </span>
            <span class="ts-dot bg-{c.id}"></span>
          </a>
        {/each}
      </div>
      <div class="px-6 py-4 border-t border-paper-edge">
        <p class="text-ink-mute m-0 text-sm" style="line-height:1.6">
          Pass through the gate and the rules are already in force. That is the point of the pair.
        </p>
      </div>
    </aside>
  </div>
</header>

<!-- ── Two planes ────────────────────────────────────────────────────── -->
<section id="planes" class="border-t border-paper-edge py-24">
  <div class="ts-inner mx-auto px-7">
    <div class="mb-12">
      <div class="flex items-baseline gap-3 mb-4">
        <span class="kanji text-primary text-2xl" style="line-height:1">分</span>
        <span class="mono text-ink-mute text-xs" style="letter-spacing:0.12em;text-transform:uppercase">Bun · to divide</span>
      </div>
      <h2 class="display text-ink m-0 text-3xl" style="font-weight:300;line-height:1.15;letter-spacing:-0.022em;max-width:720px">
        Every answer knows where it ran.
      </h2>
      <p class="text-ink-soft mt-4 m-0 text-lg" style="line-height:1.6;max-width:560px">
        The split execution plane is not a setting buried in preferences — it is written on the response, every time.
      </p>
    </div>
    <div class="ts-two-col gap-6">
      {#each PLANES as p (p.label)}
        <div class="border border-paper-edge rounded-lg bg-paper-soft p-7">
          <div class="flex items-center gap-3 mb-4">
            <span class="kanji text-primary text-xl" style="line-height:1">{p.kanji}</span>
            <span class="mono text-ink border border-paper-edge rounded-full text-xs" style="padding:3px 10px">{p.label}</span>
          </div>
          <p class="text-ink-soft m-0 text-base" style="line-height:1.65">{p.text}</p>
        </div>
      {/each}
    </div>
  </div>
</section>

<!-- ── Clients ───────────────────────────────────────────────────────── -->
<section id="clients" class="border-t border-paper-edge py-24">
  <div class="ts-inner mx-auto px-7">
    <div class="mb-12">
      <div class="flex items-baseline gap-3 mb-4">
        <span class="kanji text-primary text-2xl" style="line-height:1">二</span>
        <span class="mono text-ink-mute text-xs" style="letter-spacing:0.12em;text-transform:uppercase">Ni · two</span>
      </div>
      <h2 class="display text-ink m-0 text-3xl" style="font-weight:300;line-height:1.15;letter-spacing:-0.022em;max-width:720px">
        Two tools, one temperament.
      </h2>
      <p class="text-ink-soft mt-4 m-0 text-lg" style="line-height:1.6;max-width:560px">
        Torii is what your team opens in the morning. Seiki is where you go when you need to know why — and to change it.
      </p>
    </div>
    <div class="flex flex-col gap-8">
      {#each CLIENTS as c, i (c.id)}
        <div id={c.id} class="ts-client border border-paper-edge rounded-lg text-{c.id}"
             class:flip={i % 2 === 1} style="overflow:hidden">
          <div class="ts-client-body p-10">
            <div class="mb-6 flex items-center justify-between">
              <span class="mono text-ink-faint text-sm">{String(i + 1).padStart(2, '0')}</span>
              <span class="mono rounded-sm px-2 py-0 text-warning bg-warning-soft text-xs" style="white-space:nowrap">{c.status}</span>
            </div>
            <div class="flex items-baseline flex-wrap gap-3 mb-2">
              <span class="display text-ink text-2xl" style="font-weight:400;letter-spacing:-0.02em">{c.name}</span>
              <span class="mono text-ink-mute text-xs" style="letter-spacing:0.1em;text-transform:uppercase">{c.category}</span>
            </div>
            <p class="display text-ink m-0 text-xl" style="font-weight:300;letter-spacing:-0.015em;line-height:1.3">{c.tagline}</p>
            <p class="text-ink-soft mt-3 text-base" style="line-height:1.65;max-width:460px">{c.blurb}</p>
            <div class="flex flex-wrap gap-2 mt-6 mb-8">
              {#each c.surfaces as s (s)}
                <span class="text-ink-soft text-sm border border-paper-edge rounded-full" style="padding:4px 12px;white-space:nowrap">{s}</span>
              {/each}
            </div>
            <div class="flex flex-wrap gap-2">
              {#each c.meta as m (m)}
                <span class="mono text-ink-mute border border-paper-edge rounded-sm text-xs" style="padding:2px 7px;white-space:nowrap">{m}</span>
              {/each}
            </div>
          </div>
          <div class="ts-client-panel">
            <span class="kanji text-{c.id}" style="font-size:220px;line-height:1;opacity:0.92">{c.kanji}</span>
            <span class="mono text-ink-faint" style="position:absolute;bottom:18px;right:20px;font-size:11px;letter-spacing:0.14em">{c.gloss}</span>
          </div>
        </div>
      {/each}
    </div>
  </div>
</section>

<!-- ── Capabilities ──────────────────────────────────────────────────── -->
<section id="capabilities" class="border-t border-paper-edge py-24">
  <div class="ts-inner mx-auto px-7">
    <div class="mb-12">
      <div class="flex items-baseline gap-3 mb-4">
        <span class="kanji text-primary text-2xl" style="line-height:1">具</span>
        <span class="mono text-ink-mute text-xs" style="letter-spacing:0.12em;text-transform:uppercase">Gu · the instruments</span>
      </div>
      <h2 class="display text-ink m-0 text-3xl" style="font-weight:300;line-height:1.15;letter-spacing:-0.022em;max-width:720px">
        What the pair is made of.
      </h2>
    </div>
    <div class="ts-cap-grid gap-x-12 gap-y-12">
      {#each CAPABILITIES as c (c.title)}
        <div>
          <span class="kanji text-primary block" style="font-size:32px;line-height:1;margin-bottom:16px">{c.kanji}</span>
          <h3 class="display text-ink m-0 text-lg" style="font-weight:400;letter-spacing:-0.01em">{c.title}</h3>
          <p class="text-ink-soft mt-2 m-0 text-sm" style="line-height:1.65">{c.text}</p>
        </div>
      {/each}
    </div>
  </div>
</section>

<!-- ── Privacy ───────────────────────────────────────────────────────── -->
<section id="privacy" class="border-t border-paper-edge py-24">
  <div class="ts-inner mx-auto px-7">
    <div class="ts-split gap-16">
      <div>
        <div class="flex items-baseline gap-3 mb-4">
          <span class="kanji text-primary text-2xl" style="line-height:1">蔵</span>
          <span class="mono text-ink-mute text-xs" style="letter-spacing:0.12em;text-transform:uppercase">Zō · to keep</span>
        </div>
        <h2 class="display text-ink m-0 text-3xl" style="font-weight:300;line-height:1.15;letter-spacing:-0.022em;max-width:460px">
          Your prompts stay in your building.
        </h2>
        <p class="text-ink-soft mt-4 m-0 text-base" style="line-height:1.7;max-width:460px">
          Both clients run on your own infrastructure. There is no Sensei HQ account, no
          telemetry back to us, and no copy of your traffic anywhere we can read it.
          You hold the provider keys; you choose the region; you can export or delete
          the whole audit log whenever you like.
        </p>
      </div>
      <div class="border border-paper-edge rounded-lg bg-paper-soft p-7">
        <span class="mono text-ink-mute block mb-4 text-xs" style="letter-spacing:0.12em;text-transform:uppercase">What leaves your network</span>
        <div class="flex flex-col">
          {#each PRIVACY_ROWS as row, i (row.term)}
            <div class="ts-detail-row py-3 flex items-baseline justify-between gap-6" class:last={i === PRIVACY_ROWS.length - 1}>
              <span class="text-ink text-sm">{row.term}</span>
              <span class="text-ink-mute text-sm" style="text-align:right;max-width:240px">{row.detail}</span>
            </div>
          {/each}
        </div>
      </div>
    </div>
  </div>
</section>

<!-- ── Gateway ───────────────────────────────────────────────────────── -->
<section id="gateway" class="border-t border-paper-edge py-24">
  <div class="ts-inner mx-auto px-7">
    <div class="ts-split gap-16" style="align-items:center">
      <div>
        <div class="flex items-baseline gap-3 mb-4">
          <span class="kanji text-gateway text-2xl" style="line-height:1">基</span>
          <span class="mono text-ink-mute text-xs" style="letter-spacing:0.12em;text-transform:uppercase">Ki · the foundation</span>
        </div>
        <h2 class="display text-ink m-0 text-3xl" style="font-weight:300;line-height:1.15;letter-spacing:-0.022em;max-width:460px">
          Both are built on Gateway.
        </h2>
        <p class="text-ink-soft mt-4 m-0 text-base" style="line-height:1.7;max-width:460px">
          Gateway is our Rust library for talking to model providers: fallback chains,
          budget control, and one interface across every vendor you use. Torii and Seiki
          are what it looks like with a face on it — but the library stands alone, and
          you can build your own client on it.
        </p>
        <a href={GATEWAY_URL} target="_blank" rel="noopener" class="zs-btn zs-btn-secondary mt-6">gateway.sensei-hq.com →</a>
      </div>
      <div class="border border-paper-edge rounded-lg bg-paper-soft p-7">
        <span class="mono text-ink-mute block mb-4 text-xs" style="letter-spacing:0.12em;text-transform:uppercase">What Gateway handles</span>
        <div class="flex flex-col">
          {#each GATEWAY_ROWS as row, i (row.term)}
            <div class="ts-detail-row py-3 flex items-baseline justify-between gap-6" class:last={i === GATEWAY_ROWS.length - 1}>
              <span class="text-ink text-sm">{row.term}</span>
              <span class="text-ink-mute text-sm" style="text-align:right;max-width:240px">{row.detail}</span>
            </div>
          {/each}
        </div>
      </div>
    </div>
  </div>
</section>

<!-- ── Contact ───────────────────────────────────────────────────────── -->
<section id="contact" class="border-t border-paper-edge py-24">
  <div class="mx-auto px-7 text-center" style="max-width:720px">
    <span class="kanji text-primary block" style="font-size:40px;line-height:1;margin-bottom:20px">入</span>
    <h2 class="display text-ink m-0 text-3xl" style="font-weight:300;line-height:1.15;letter-spacing:-0.022em">
      Torii and Seiki are in private beta.
    </h2>
    <p class="text-ink-soft mt-4 m-0 text-lg" style="line-height:1.6">
      Tell us how your organization works and we will tell you honestly whether the gate fits yet.
    </p>
    <div class="flex items-center justify-center flex-wrap gap-3 mt-8">
      <a href="mailto:hi@sensei-hq.com" class="zs-btn zs-btn-primary zs-btn-lg">
        <span class="kanji text-on-primary" style="font-size:15px;line-height:1">文</span>
        Request access
      </a>
      <a href="{base}/" class="zs-btn zs-btn-secondary zs-btn-lg">See the whole workshop</a>
    </div>
    <a href="mailto:hi@sensei-hq.com" class="mono text-ink-mute mt-4 inline-block text-sm" style="letter-spacing:0.02em;white-space:nowrap">hi@sensei-hq.com</a>
  </div>
</section>

<!-- ── Footer ────────────────────────────────────────────────────────── -->
<footer class="border-t border-paper-edge">
  <div class="ts-inner mx-auto px-7 py-16 flex items-center justify-between flex-wrap gap-4">
    <a href="{base}/" class="flex items-center gap-3 no-underline">
      <span class="i-brand:sensei-hq text-primary block flex-shrink-0" style="width:24px;height:24px" aria-hidden="true"></span>
      <span class="flex items-baseline gap-2">
        <span class="display text-ink text-base">Sensei</span>
        <span class="mono text-ink-mute text-xs" style="letter-spacing:0.08em">HQ</span>
      </span>
    </a>
    <span class="mono text-ink-faint text-xs">門 · Torii · Seiki · built on Gateway</span>
  </div>
</footer>

<style>
  .ts-inner {
    max-width: 1120px;
  }
  .ts-nav-wrap {
    background: color-mix(in oklch, var(--paper) 80%, transparent);
    backdrop-filter: blur(14px) saturate(150%);
    -webkit-backdrop-filter: blur(14px) saturate(150%);
    -webkit-mask-image: linear-gradient(to bottom, #000 72%, transparent);
    mask-image: linear-gradient(to bottom, #000 72%, transparent);
    padding-bottom: 6px;
  }
  .ts-nav-link {
    transition: color 0.15s;
  }
  .ts-nav-link:hover {
    color: var(--ink);
  }
  .ts-hero-grid {
    display: grid;
    grid-template-columns: 1.55fr 1fr;
    align-items: start;
  }
  .ts-pair-row {
    display: grid;
    grid-template-columns: auto 1fr auto;
    align-items: center;
    border-top: 1px solid var(--paper-edge);
    transition: background 0.15s;
  }
  .ts-pair-row:first-child {
    border-top: none;
  }
  .ts-pair-row:hover {
    background: var(--paper-mute);
  }
  .ts-dot {
    display: inline-block;
    width: 8px;
    height: 8px;
    border-radius: 50%;
    flex-shrink: 0;
  }
  .ts-two-col {
    display: grid;
    grid-template-columns: 1fr 1fr;
  }
  .ts-cap-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
  }
  .ts-split {
    display: grid;
    grid-template-columns: 1fr 1fr;
    align-items: start;
  }
  .ts-client {
    display: grid;
    grid-template-columns: 1.3fr 1fr;
    transition: border-color 0.18s;
  }
  .ts-client.flip {
    grid-template-columns: 1fr 1.3fr;
  }
  .ts-client.flip .ts-client-body {
    order: 2;
  }
  .ts-client.flip .ts-client-panel {
    order: 1;
    border-left: none;
    border-right: 1px solid var(--paper-edge);
  }
  .ts-client-panel {
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--paper-mute);
    position: relative;
    min-height: 340px;
    overflow: hidden;
    border-left: 1px solid var(--paper-edge);
  }
  .ts-detail-row {
    border-bottom: 1px solid var(--paper-edge);
  }
  .ts-detail-row.last {
    border-bottom: none;
  }
  @media (max-width: 900px) {
    .ts-hero-grid,
    .ts-two-col,
    .ts-split,
    .ts-cap-grid,
    .ts-client,
    .ts-client.flip {
      grid-template-columns: 1fr;
    }
    .ts-client.flip .ts-client-panel {
      order: 2;
      border-right: none;
    }
    .ts-client-panel {
      border-left: none;
      border-top: 1px solid var(--paper-edge);
      min-height: 220px;
    }
  }
</style>
